apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: node-backend
    type: service 
spec: 
  type: NodePort
  selector:
    app: node-backend
  ports:
  - name: node-service
    protocol: TCP
    port: 3000
    targetPort: 3000